error: Create the error_is_set function
This function is to be used in **errp pointer to check if *errp is not NULL
that would means that an error is set.

Signed-off-by: Benoît Canet <benoit.canet@nodalink.com>